### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by jbanlles-vunkers** [thingsboard/flutter_thingsboard_app#178]
Hello, how could I make it so that when I enter the app, I go directly to a dashboard panel, the one I specify?

Thank you

**Comment by ybeshkarov** [comment]
Hi,
Based on your needs, you may set the default or home dashboard to your user.
<img width="1724" alt="Screenshot 2024-12-31 at 10 56 50" src="https://github.com/user-attachments/assets/322c82c3-4c54-44e6-a0a4-1c4789eae1e2" />

**Comment by jbanlles-vunkers** [comment]
Thanks!

**Comment by jbanlles-vunkers** [comment]
What I want to achieve is that when the app opens it goes directly to the panel without going through the dashboard

**Comment by ybeshkarov** [comment]
A home dashboard is when a user, instead of a dashboard grid, sees a selected dashboard and that's it.
A default dashboard is when a dashboard opens automatically for a user, but the user is still able to close it and see a dashboard grid.

For me, it seems a home dashboard feature is more suitable for you.
